### ISSUE TITLE
How to play and Leaderboard Buttons

### ISSUE THREAD

**Issue by swamimalode07** [swamimalode07/SimonsaysGame#1]
Place How to Play and Leaderboard Buttons Properly according to the UX

**Comment by Buddha-11** [comment]
I would like to contribute to this task , can you give a rough idea about how do you want the UX or do I have the creative freedom here to build upon the rest of the game . Would appreciate if you assign this task to me in hacktoberfest

**Comment by swamimalode07** [comment]
I basically want proper placement of How to play and Leaderboard buttons cause they are not placed properly and overlapping when screen size is changed but it should not change the color scheme and USer interface of website

**Comment by Buddha-11** [comment]
Sure please assign it to me

**Comment by swamimalode07** [comment]
yeah i've assigned it to you,Make sure to add images or videos of your before and after PR
