### ISSUE TITLE
refactoring backend 

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [swamimalode07/SimonsaysGame#12]
I’ve improved the backend by refactoring it for better readability. Hope u like it :)

The App.js is much more compact now .

<img width="1428" alt="Screenshot 2024-10-01 at 2 28 34 AM" src="https://github.com/user-attachments/assets/c6672988-14de-4112-ae39-1546874779d1">

**Comment by T-Rahul-prabhu-38** [comment]
can u assist me with creating a PR, im not able to create one.

**Comment by swamimalode07** [comment]
YEah you can go in the PR requests and make a new Pull Request but make sure it does not conflict with previous main branch
