### ISSUE TITLE
Missing .gitignore Files Leading to Potential Build Failures

### ISSUE THREAD

**Issue by rishyym0927** [swamimalode07/SimonsaysGame#16]
**Description**: 

It has been observed that `.gitignore` files are missing from the repository. This can lead to unintended files such as environment variables, build artifacts, and local configurations being tracked by Git, which may cause:

- Increased repository size.
- Exposure of sensitive data.
- Build failures due to platform-specific files.

**Solution**:  
Create and add `.gitignore` files to appropriately exclude unnecessary files like `node_modules/`, `build/`, environment variables, and local settings.

This will help ensure the repository remains clean and consistent across different environments.

**Comment by rishyym0927** [comment]
Please label this under hacktoberfest and assign me this issue.

**Comment by swamimalode07** [comment]
gitignore file is in the repo but it is not shown on github

**Comment by rishyym0927** [comment]
It's always a good practice to include a .gitignore file in your repository as most of the people forget to add initialize and push unnecessary module in their repo

**Comment by swamimalode07** [comment]
sure send me a screenshot for your gitignore files ,i'll consider merging it

**Comment by rishyym0927** [comment]
the gitignore file is added but to avoid failures i want to write some more files, can you first assign me this issue.
