### ISSUE TITLE
Missing process.env File Can Cause Application to Break

### ISSUE THREAD

**Issue by rishyym0927** [swamimalode07/SimonsaysGame#17]
**Description**: 

The project currently lacks a `.env` file for handling environment variables. This can lead to issues when the application requires environment-specific settings (such as API keys or database configurations) and result in the application failing during runtime.

**Proposed Solution**:

- Create a `.env` file to store environment-specific variables.
- Ensure `process.env` is used to reference these variables throughout the project.
- Update the `.gitignore` file to exclude the `.env` file from being committed.
- Provide documentation or an example `.env.sample` file to help contributors set up their environment variables correctly.

**Bold Label**: _Hacktoberfest_

**Assign to me with the proposed solution outlined above.**

**Comment by Buddha-11** [comment]
I think the code base has a .env file but its not pushed on the repo using .gitignore . env variables are being used in app.cjs

**Comment by rishyym0927** [comment]
> I think the code base has a .env file but its not pushed on the repo using .gitignore . env variables are being used in app.cjs

You need to include a process.env file to help contributors understand which environment variables are necessary to run the project, as it currently lacks this information

**Comment by swamimalode07** [comment]
Yeah it has a .env file but it is not shown in the repo cause github blocks the .env file

**Comment by rishyym0927** [comment]
> Yeah it has a .env file but it is not shown in the repo cause github blocks the .env file

Im not talking about .env file, im saying process.env should be there for contributors to understanf what variable are required to run the project

**Comment by swamimalode07** [comment]
Sure make sure to paste screenshots here before and after the PR request

**Comment by rishyym0927** [comment]
please assign the issue first
