### ISSUE TITLE
Separate CSS Files from Inline Styles

### ISSUE THREAD

**Issue by rishyym0927** [swamimalode07/SimonsaysGame#20]
**Title**: Separate CSS Files from Inline Styles

**Description**:

The current implementation uses inline CSS for styling, which hinders maintainability and readability. To enhance the project's structure and facilitate easier updates, it is essential to separate the CSS into distinct stylesheet files.

**Proposed Solution**:

- Identify all instances of inline CSS within the project.
- Create separate CSS files for different components or pages as needed.
- Link the CSS files to the respective components to replace the inline styles.
- Ensure that the styles maintain the current design and functionality after the separation.

**Bold Label**: _Hacktoberfest_

**Assign to me with the proposed solution outlined above.**

**Comment by swamimalode07** [comment]
Sure rishyym but , make sure it does not affect the user interface or does not affect the current styling
