### ISSUE TITLE
Enhance Font Style for Improved Visual Appeal

### ISSUE THREAD

**Issue by manthanmk66** [swamimalode07/SimonsaysGame#36]
The current font is functional and readable, but it lacks a distinctive style that could enhance the overall design and feel of the application. Let's explore and add a more unique, visually appealing font that still maintains readability while giving the UI a more polished and modern look.

**Comment by swamimalode07** [comment]
Sure , i'll assign you this PR just make sure to avoid conflicts and provide  a screenshot of your changes before and after PR

**Comment by manthanmk66** [comment]
i have commited  and updated the changes you can merge it now
