### ISSUE TITLE
Add Error page

### ISSUE THREAD

**Issue by bhaavvya** [swamimalode07/SimonsaysGame#44]
Description:-
Adding an error page so that when a user goes to wrong url, the user will be redirected to the error page.
like this , i mean not this but an example of error page
![image](https://github.com/user-attachments/assets/6f159e6c-a222-45d3-9e80-068ea4c1027f)
will be making a new error page design according to the website.

@swamimalode07 , please assign me this issue under hacktoberfest 2k24.

**Comment by swamimalode07** [comment]
Sure i assign you this issue , just make sure you keep the UI consistency and the error page is playful like the game UI , make sure to add screenshots before and after PR

**Comment by bhaavvya** [comment]
I did the task

https://github.com/user-attachments/assets/6c80c918-682f-453a-aac7-586585b7aa48

should i open a pr?
because i had already opened a pr and maybe after its merged then it may create a merge conflict for this pr(I'm not sure if it give merge conflict but still).
