### ISSUE TITLE
Add Timer to the game

### ISSUE THREAD

**Issue by bhaavvya** [swamimalode07/SimonsaysGame#45]
Description:-
Adding timer to the game will make it more challenging and interesting. Timer will start as soon as the game starts.

@swamimalode07 , please assign me issue under hacktoberfest 2k24.

**Comment by swamimalode07** [comment]
Sure i assign you this task under hactoberfest , make sure to add screenshots before and after PR 
 Your contributinn should not have any conflicts with the main branch
and make sure you dont change anything in the database
